<article class="col-12 col-sm-6 col-md-4">
      <div class="card mb-3">
      <a href="<?= "?page=detail&id=".$pic['id'] ?>">
        <img src="<?= $pic['src'] ?>" class="card-img-top" alt="<?= $pic['title'] ?>">
      </a>
        <div class="card-body">
        <a class="text-dark text-decoration-none" href="<?= "?page=detail&id=".$pic['id'] ?>">
          <h4 class="card-title"><?= $pic['title'] ?></h4>
        </a>
          <p class="card-text"><?= $pic['description'] ?></p>
          <p class="card-text fst-italic fw-light">
            Created At: <?= $pic['created_at'] ?>
          <br>
          Updated At: <?= $pic['updated_at'] ?>
          </p>
          <p class="card-text">&#x2015; <?= $pic['author'] ?></p>
          <a href="<?= "?page=detail&id=".$pic['id'] ?>" class="btn btn-secondary">Read more</a>
        </div>
      </div>
    </article>