<?php
/**
 * Il peut s'avérer pratique de récupérer ici $data
 * Et éventuellement de déclarer des variables de traitement
 * */
$pic = $data['picture'];
?><h1 class="mb-3 text-center">Admin Update Picture</h1>
<form method="POST" action="?page=picture&action=edit&id=<?= $pic['id'] ?>">
<div class="mb-3">
  <label for="title" class="form-label">Title</label>
  <input value="<?= $pic['title'] ?>" type="text" class="form-control" name="title" id="title" placeholder="Title">
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <input value="<?= $pic['description'] ?>" type="text" class="form-control" name="description" id="description" placeholder="Description">
</div>
<div class="mb-3">
  <label for="src" class="form-label">Source</label>
  <input value="<?= $pic['src'] ?>" type="text" class="form-control" name="src" id="src" placeholder="URL Source">
</div>
<div class="mb-3">
  <label for="author" class="form-label">Author</label>
  <input value="<?= $pic['author'] ?>" type="text" class="form-control" name="author" id="author" placeholder="Author">
</div>
<div class="mb-3">
  <input type="submit" class="btn btn-primary" name="submit" value="Update Picture">
</div>
</form>