<?php

/**
 * Il peut s'avérer pratique de récupérer ici $data
 * Et éventuellement de déclarer des variables de traitement
 * */
$errors = $data['errors'];
$isKeyValidated = $data['isKeyValidated'];
$isPasswordUpdated = $data['isPasswordUpdated'];
?><h1 class="text-center">Define Your New Password</h1>

<?php if (!empty($errors)) : ?>
    <div class="alert alert-danger" role="alert">
        <?php foreach ($errors as $error) : ?>
            <p><?= $error ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if ($isKeyValidated) : ?>
    <?php if (!$isPasswordUpdated) : ?>
        <form method="POST" id="registration_form">
            <div class="mb-3">
                <label for="src" class="form-label">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                <p><input type="checkbox" onclick="toggleVisible('password')"> Afficher</p>
            </div>
            <div class="mb-3">
                <label for="confirm_password" class="form-label">Confirm Password</label>
                <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="Confirm Password">
                <p><input type="checkbox" onclick="toggleVisible('confirm_password')"> Afficher</p>
            </div>
            <div class="mb-3">
                <input type="button" class="btn btn-primary" name="registration_btn" id="registration_btn" value="Change Password">
            </div>
        </form>
    <?php else : ?>
        <div class="alert alert-success" role="alert">
            Mot-de-passe modifié !!! Vous pouvez vous <a href="?page=login">connecter</a> desormais.
        </div>
    <?php endif; ?>
<?php else : ?>
    <div class="alert alert-danger" role="alert">
    <p>Opération impossible vous êtes un imposteur et vous avez été démasqué ou la clé est expirée... au choix !</p>
    </div>
<?php endif; ?>
<script>
    function toggleVisible(id) {
        const x = document.getElementById(id);
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
    const password = document.getElementById("password");
    const confirmPassword = document.getElementById("confirm_password");
    const registerBtn = document.getElementById("registration_btn");
    const registerForm = document.getElementById("registration_form");

    if (registerBtn !== null) {
        registerBtn.addEventListener("click", () => {
            if (password.value != "" && password.value != confirmPassword.value) {
                alert("Password & Confirm password do not match !");
                return false;
            }
            registerForm.submit();
        });
    }
</script>